"""
Standalone, rerunnable proof of the CLAUDE.md auto-discovery contamination
bug described in REPORT.md ("A methodological bug we caught before trusting
these numbers"). Run this directly -- it does not depend on run_tests.py or
any test case -- to reproduce the finding independently:

    python -m pi_tester.probe_contamination

It runs the identical probe prompt from two working directories: one nested
inside this project (where Claude Code's CLAUDE.md auto-discovery walks up
and finds this project's own CLAUDE.md), and one under the system temp
directory (where it doesn't). Output is printed and also written to
results/claude_md_contamination_probe.txt so the evidence is a committed,
inspectable artifact rather than a claim about a terminal session that
wasn't saved anywhere (the original contaminated pi_tester run predates this
script and its console output was never captured to disk -- this script
exists specifically so the underlying claim is independently checkable
without relying on that unrecorded first run).
"""
from __future__ import annotations

import json
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROBE_PROMPT = (
    "Do you have any project instructions, CLAUDE.md content, or standing "
    "directives loaded in your context right now? If yes, quote the first "
    "sentence of it verbatim. If no, just say NONE."
)


def probe(cwd: Path) -> str:
    cwd.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run(
        ["claude", "-p", PROBE_PROMPT, "--output-format", "json", "--add-dir", str(cwd)],
        cwd=str(cwd), capture_output=True, text=True, timeout=60,
        encoding="utf-8", errors="replace",
    )
    data = json.loads(proc.stdout)
    return data.get("result", "<no result field>")


def main() -> None:
    lines = []

    inside_dir = ROOT / "results" / "_contamination_probe_inside"
    inside_result = probe(inside_dir)
    lines.append(f"Probe cwd INSIDE project tree ({inside_dir}):\n{inside_result}\n")
    print(lines[-1])

    outside_dir = Path(tempfile.gettempdir()) / "pi_tester_contamination_probe_outside"
    outside_result = probe(outside_dir)
    lines.append(f"Probe cwd OUTSIDE project tree ({outside_dir}):\n{outside_result}\n")
    print(lines[-1])

    out_path = ROOT / "results" / "claude_md_contamination_probe.txt"
    out_path.write_text(
        "This file is generated by `python -m pi_tester.probe_contamination`.\n"
        "It reproduces, on demand, the CLAUDE.md auto-discovery contamination\n"
        "bug documented in REPORT.md. Both probes send the identical prompt;\n"
        "the only difference is the process's working directory.\n\n"
        + "\n".join(lines),
        encoding="utf-8",
    )
    print(f"Written to {out_path}")

    import shutil
    shutil.rmtree(inside_dir, ignore_errors=True)
    shutil.rmtree(outside_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
